# Generated by Django 5.2.8 on 2025-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_time',
            field=models.TimeField(default='21:00:00'),
        ),
    ]
